name: Main Branch CI

on:
  push:
    branches: [main]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo 
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          load: true
          context: ./
          file: ./Dockerfile
          tags: valainisgt/docker-gocd-agent-debian-10-dotnet-5:v21.1.0

      - name: Test .NET is installed 
        run: set -e && docker run --rm --pull never valainisgt/docker-gocd-agent-debian-10-dotnet-5:v21.1.0 /bin/bash -c 'dotnet --version'

      - name: Scan Image
        uses: azure/container-scan@v0
        with:
          image-name: valainisgt/docker-gocd-agent-debian-10-dotnet-5:v21.1.0